# vi: set ft=ruby :
# -*- ruby -*-

require "ipaddr"


def successive_ips(base_ip, num_of_successive_ips)
  ip = base_ip.clone
  num_of_successive_ips.times.map { |n| ip = ip.succ; ip }
end

base_ip = "192.168.180.10"
boxname = "ubuntu/bionic64"
box_version = "20201123.0.0"

default_loaddriver_cpus = 2
default_target_cpus = ENV.fetch("VAGRANT_TARGET_CPUS", "2")
default_target_node_count = 3
target_node_ip_addresses = successive_ips(base_ip, default_target_node_count)
# Memory settings in MB
default_load_driver_memory = ENV.fetch("VAGRANT_LOAD_DRIVER_MEMORY", "2048")
default_target_memory = ENV.fetch("VAGRANT_TARGET_MEMORY", "5120")

install_build_requirements = ENV["VAGRANT_ENABLE_BUILD"].to_s.downcase=="true"
domain_name = "benchmarks.ci.vagrant"

nodes = [{ hostname: "coordinator", domain: domain_name, autostart: true, box: boxname, box_version: box_version, memory: default_load_driver_memory, cpus: default_loaddriver_cpus }]

# target-nodes
for i in 1..default_target_node_count
  nodes += [{ hostname: "target%02d" % [i], domain: domain_name, autostart: true, box: boxname, box_version: box_version, memory: default_target_memory.to_i, cpus: default_target_cpus }]
end

rally_repo = ENV.fetch("RALLY_REPO", "https://github.com/elastic/rally.git")
rally_branch = ENV.fetch("RALLY_BRANCH", "master")
rally_sha = ENV.fetch("RALLY_SHA", "")

def disable_apt_frontend
  <<~EOF
    set -eo pipefail
    sed -i 's/\(dpkg-preconfigure\) --apt/\1 --frontend=noninteractive --apt/' /etc/apt/apt.conf.d/70debconf
  EOF
end

def curl_wrapper(max_time=10, retry_max_time=100, silent=true)
  # Return a curl command prefix that always retries on failure
  basic_command = "curl -SfL --connect-timeout 5 --max-time #{max_time} --retry 5 --retry-max-time #{retry_max_time}"
  if silent
    return basic_command << " -s"
  else
    return basic_command
  end
end

def rally_sudoers
  # Use single quotes to avoid interpolating EOF2 intended for bash
  # tilde before 'EOF' allows indenting heredoc without passing the extra leading spaces to actual bash command
  <<~'EOF'
    set -eo pipefail
    cat >/etc/sudoers.d/rally_user <<EOF2
    Defaults:rally !requiretty
    rally ALL = (ALL) NOPASSWD: ALL
    EOF2
  EOF
end

def install_jenkins_user
  <<~EOF
    set -eo pipefail
    groupadd -g 1010 jenkins
    useradd -u 1010 -g 1010 -s /bin/bash -m -k /etc/skel -d /var/lib/jenkins jenkins
    mkdir /var/lib/jenkins/.ssh

    cp /night_rally/night_rally/fixtures/ansible/.vagrantssh/id_rsa /var/lib/jenkins/.ssh/rally
    cp /night_rally/night_rally/fixtures/ansible/.vagrantssh/id_rsa.pub /var/lib/jenkins/.ssh/authorized_keys
    chown -R jenkins:jenkins /var/lib/jenkins/.ssh
    chmod -R 0600 /var/lib/jenkins/.ssh/rally
  EOF
end

def install_rally_user
  <<~EOF
    set -eo pipefail
    groupadd -g 1011 rally
    useradd -u 1011 -g 1011 -s /bin/bash -m -k /etc/skel -d /home/rally rally
    mkdir /home/rally/.ssh

    cp /night_rally/night_rally/fixtures/ansible/.vagrantssh/id_rsa /home/rally/.ssh/rally
    cp /night_rally/night_rally/fixtures/ansible/.vagrantssh/id_rsa.pub /home/rally/.ssh/authorized_keys
    chown -R rally:rally /home/rally/.ssh
  chmod -R 0600 /home/rally/.ssh/rally
  EOF
end

def install_vault
  <<~EOF
    set -eo pipefail
    CUR_HOME=$HOME
    #{curl_wrapper} -o ${CUR_HOME}/vault.zip https://releases.hashicorp.com/vault/1.1.1/vault_1.1.1_linux_amd64.zip
    sudo unzip ${CUR_HOME}/vault.zip -d /usr/local/bin
    sudo chmod +x /usr/local/bin/vault
    rm ${CUR_HOME}/vault.zip
  EOF
end

def install_rally_source(rally_repo, rally_branch, rally_sha)
  # Remove OS packages for python3-pip and python3-setuptools; we prefer per account installation of pip3
  <<~EOF
    set -eo pipefail
    apt-get update
    apt-get purge -y python3\*-pip python3\*-setuptools
    apt-get install -y build-essential curl libbz2-dev libncurses5-dev libncursesw5-dev libreadline-dev libsqlite3-dev libssl-dev llvm wget xz-utils zlib1g-dev unzip jq
    cat >/rally-install.sh <<'EOF2'
    #!/usr/bin/env bash

    cd /var/lib/jenkins
    #{curl_wrapper} https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer -o pyenv-installer
    bash ./pyenv-installer
    rm pyenv-installer
    echo 'export PATH="$HOME/.pyenv/bin:$PATH"' >> /var/lib/jenkins/.profile
    echo 'eval "\$(pyenv init -)"' >> /var/lib/jenkins/.profile
    echo 'eval "\$(pyenv virtualenv-init -)"' >> /var/lib/jenkins/.profile
    source /var/lib/jenkins/.profile
    pyenv install 3.8.0
    pyenv local 3.8.0
    echo 'pyenv local 3.8.0' >> /var/lib/jenkins/.profile
    mkdir src bin
    cd src
    git clone #{rally_repo} --branch #{rally_branch}
    cd rally
    if [[ ! -z \"#{rally_sha}\" ]]; then git checkout #{rally_sha}; fi
    python3 -m pip install --upgrade pip setuptools wheel
    python3 -m pip install --quiet --user --upgrade --editable . --use-feature=2020-resolver
    cd /var/lib/jenkins
    ln -s $PWD/src/rally/rally $PWD/bin/rally
    ln -s $PWD/src/rally/rallyd $PWD/bin/rallyd
    ln -s $PWD/night_rally/night_rally.sh $PWD/bin/night_rally
    EOF2

    chmod ugo+x /rally-install.sh
    sudo -iu jenkins /rally-install.sh
  EOF
end

def tweak_es_sysctl
  <<~EOF
    # Tweak sysctl so ES will start.
    grep -q '^vm.max_map_count=' /etc/sysctl.conf || ( \
      echo 'vm.max_map_count=262144' >> /etc/sysctl.conf && \
      sysctl --load \
    )
  EOF
end

def install_night_rally_test_script(base_ip, target_node_ip_addresses)
  <<~EOF
    cat >/var/lib/jenkins/env_test_script <<'EOF2'
    #export FIXTURES=drop-caches,trim,initialize-data-disk
    # Speed things up by starting with zero string fixtures, but allow overriding via env var
    export FIXTURES=${FIXTURES:-}
    export COORDINATING_NODES=#{base_ip}
    export TARGET_HOSTS="#{target_node_ip_addresses.join(',')}"
    export TEST_MODE=YES
    EOF2

    cat >/var/lib/jenkins/test_nightly.sh <<"EOF2"
    #!/usr/bin/env bash
    set -eo pipefail
    source /var/lib/jenkins/env_test_script
    # release-license is basic just because it's the default option in the JJB dropdown; ignored in nightly mode but used to copy the results as master in release charts
    night_rally --target-host="${TARGET_HOSTS}" --race-configs="resources/race-configs-group-1.json" --effective-start-date="" --mode="nightly" --version="master" --release-license="basic" --release-x-pack-components="" --runtime-jdk="bundled"
    night_rally --target-host="${TARGET_HOSTS}" --race-configs="resources/race-configs-group-2.json" --effective-start-date="" --mode="nightly" --version="master" --release-license="basic" --release-x-pack-components="" --runtime-jdk="bundled"
    EOF2

    cat >/var/lib/jenkins/test_release.sh <<"EOF2"
    #!/usr/bin/env bash
    set -eo pipefail
    source /var/lib/jenkins/env_test_script
    night_rally --target-host="${TARGET_HOSTS}" --race-configs="resources/race-configs-group-1.json" --effective-start-date="" --mode="release" --version="6.8.7" --release-license="basic" --release-x-pack-components="" --runtime-jdk="15"
    night_rally --target-host="${TARGET_HOSTS}" --race-configs="resources/race-configs-group-2.json" --effective-start-date="" --mode="release" --version="6.8.7" --release-license="basic" --release-x-pack-components="" --runtime-jdk="15"
    EOF2

    cat >/var/lib/jenkins/test_longrunning.sh <<"EOF2"
    #!/usr/bin/env bash
    set -eo pipefail
    source /var/lib/jenkins/env_test_script
    /var/lib/jenkins/night_rally/external/scripts/long-running-benchmarks.sh
    EOF2

    chown jenkins:jenkins /var/lib/jenkins/test_*.sh
    chmod +x /var/lib/jenkins/test_*.sh
  EOF
end

def install_java(major_ver)
  <<~EOF
    set -eo pipefail
    jdk_url=$(#{curl_wrapper} https://jvm-catalog.elastic.co/jdk/latest_openjdk_#{major_ver}_linux | jq -r .url)
    cd /var/lib/jenkins
    mkdir -p .java/openjdk#{major_ver}
    cd .java/openjdk#{major_ver}
    #{curl_wrapper(max_time=300,retry_max_time=1800,silent=false)} --progress-bar -o java#{major_ver}.tgz $jdk_url
    tar zxf java#{major_ver}.tgz --strip-components=1
    rm -f java#{major_ver}.tgz
    cd ../../
    chown -R jenkins:jenkins .java
  EOF
end

def pass_additional_jenkins_env_vars
  <<~EOF
    set +x -eo pipefail
    cat >>/var/lib/jenkins/.profile <<EOF2
    export VAULT_ADDR=https://secrets.elastic.co:8200
    export RALLY_METRICS_STORE_CREDENTIAL_PATH=${RALLY_METRICS_STORE_CREDENTIAL_PATH:-/secret/rally/cloud/vagrant-test-rally-metrics}
    export IN_VAGRANT=YES
    EOF2
  EOF
end

def install_docker
  <<~EOF
    set -eo pipefail
    # Remove older Docker versions
    apt-get remove -y \
      docker \
      docker-engine \
      docker.io \
      containerd \
      runc
    # Install and configure Docker
    apt-get install -y \
      apt-transport-https \
      ca-certificates \
      curl \
      gnupg-agent \
      software-properties-common && \
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1 apt-key add - && \
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" && \
    apt-get update && \
    apt-get install -y docker-ce docker-ce-cli containerd.io && \
    usermod -aG docker jenkins && \
    systemctl enable docker && \
    systemctl start docker
    curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose
  EOF
end

def install_ansible(ansible_version)
  <<~EOF
    sudo -iu jenkins bash -c "python3 -m pip install --user ansible==#{ansible_version}"
  EOF
end

Vagrant.configure(2) do |config|
  use_cachier = false
  if Vagrant.has_plugin?('vagrant-cachier') and not ENV['VAGRANT_NO_CACHIER']
    use_cachier = true
    config.cache.scope = :machine
  end

  ENV['VAGRANT_FORCE_REFRESH_CACHE'] = 'true'
  ip_address = IPAddr.new base_ip

  nodes.each do |node|

    fqdn = node[:hostname] + '.' + node[:domain]

    config.vm.define node[:hostname], autostart: (node[:autostart] || false) do |node_config|
      node_config.vm.box = node[:box] || boxname
      node_config.vm.box_version = box_version
      node_config.vm.hostname = fqdn
      node_config.vm.network :private_network, ip: ip_address.to_s

      node_config.vm.provider :virtualbox do |vbox, override_config|
        vbox.name = fqdn
        vbox.memory = node[:memory] || default_memory
        vbox.cpus = node[:cpus]
        override_config.vm.synced_folder '../../..', '/night_rally'

        file_to_disk = File.realpath("vagrantdisk").to_s + "/#{node[:hostname]}_disk.vdi"
        vbox.customize ['createmedium', "disk", '--filename', file_to_disk, '--size', 20480, '--format', 'VDI'] # Size is in MiB
        vbox.customize ['storageattach', :id, '--storagectl', 'SCSI', '--port', 2, '--device', 0, '--type', 'hdd', '--medium', file_to_disk]

        if node[:hostname] == "coordinator"
          override_config.vm.synced_folder "#{Dir.home}/", "/home/vagrant/", type: "rsync", rsync__args: ["-r", "--include=.vault-token", "--exclude=*"]
        end
      end

      node_config.ssh.forward_agent = true
      node_config.vm.provision "shell", inline: disable_apt_frontend
      node_config.vm.provision "shell", inline: tweak_es_sysctl
      node_config.vm.provision "shell", inline: install_jenkins_user
      node_config.vm.provision "shell", inline: pass_additional_jenkins_env_vars, env: {"RALLY_METRICS_STORE_CREDENTIAL_PATH" => ENV["VAULT_NIGHT_RALLY_METRICS_STORE_CREDENTIAL_PATH"]}
      node_config.vm.provision "shell", inline: install_rally_user
      node_config.vm.provision "shell", inline: rally_sudoers
      node_config.vm.provision "shell", inline: install_rally_source(rally_repo, rally_branch, rally_sha)

      node_config.vm.provision "shell", inline: <<-EOF
        mkfs.ext4 /dev/sdc
        mkdir -p /var/lib/jenkins/.rally/benchmarks/races
        echo "/dev/sdc /var/lib/jenkins/.rally/benchmarks/races ext4 defaults 0 2" >>/etc/fstab
        mount /var/lib/jenkins/.rally/benchmarks/races
        chown -R jenkins:jenkins /var/lib/jenkins/.rally
      EOF

      # Make a local copy of night_rally under the jenkins user home dir on the coordinator
      # required because installing night_rally needs write access to the `.egg` directory
      if node == nodes.first
        node_config.vm.provision "shell", inline: install_vault
        node_config.vm.provision "shell", inline: <<-EOF
          echo 'sudo rsync -r -o -g --chown=jenkins:jenkins --exclude ".vagrant" --exclude ".venv" --exclude "vagrantdisk" /night_rally /home/vagrant/.vault-token /var/lib/jenkins/' \
            >/home/vagrant/update_jenkins_night_rally.sh
          chmod +x update_jenkins_night_rally.sh
          ./update_jenkins_night_rally.sh

          sudo -iu jenkins bash -c 'cd night_rally; make install'
        EOF

        node_config.vm.provision "shell", inline: install_ansible("2.9.6")
      end

      node_config.vm.provision "shell", inline: install_night_rally_test_script(base_ip, target_node_ip_addresses)

      # Install docker on target nodes
      if node != nodes.first
        node_config.vm.provision "shell", inline: install_docker
      end

      # Java 11 is used by default for release benchmarks, so should be installed always
      # https://github.com/elastic/night-rally/issues/114#issuecomment-534100792
      if node != nodes.first
        node_config.vm.provision "shell", inline: install_java(11)
      end

      if node != nodes.first && install_build_requirements
        node_config.vm.provision "shell", inline: install_java(15)
      end

      ip_address = ip_address.succ
    end
  end
end
